services:
  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    volumes:
      - ./client:/app
      - app_node_modules:/app/node_modules
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
volumes:
  app_node_modules:
